"""use datetime and add original_classification field

Revision ID: 5c3b756ed022
Revises: e50c369c6ca8
Create Date: 2026-03-31 13:03:40.559094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3b756ed022'
down_revision: Union[str, Sequence[str], None] = 'e50c369c6ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landslides', sa.Column('original_classification', sa.String(), nullable=False))
    op.alter_column('landslides', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('landslides', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('landslides', 'original_classification')
    # ### end Alembic commands ###
