"""add version table

Revision ID: e50c369c6ca8
Revises: 1fc1738312c6
Create Date: 2026-03-30 10:59:41.605491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e50c369c6ca8'
down_revision: Union[str, Sequence[str], None] = '1fc1738312c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_with_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version')
    # ### end Alembic commands ###
